### ISSUE TITLE
Add "Backport Priority" field in "Code Review Request" transition

### ISSUE THREAD

**Issue by esanzp** [node-gh/gh-jira#47]
I would like you to add a new field called "Backport Priority" when a ticket is transitioned executing "Code Review Request". The field has just been implemented in JIRA. It has to be like assignee field  which displays a list of possible reviewers. 
The values/options to be choosen are the following:
1- High
2- Medium
3- Low
4- Cannot be backported for technical reasons

Thank you,
Esther

**Comment by henvic** [comment]
This feature is not required anymore by our team.
