### ISSUE TITLE
default comment use non-default jira markdown ?

### ISSUE THREAD

**Issue by maxandersen** [node-gh/gh-jira#52]
When running `gh jira pr #123` a default comment gets added to jira stating:

```
{markdown}Just started reviewing <br><br>![NodeGH](http://nodegh.io/images/octocat.png) *Sent from [GH](http://nodegh.io).*{markdown} 
```

Why are these {markdown} elements showing up ? is it assuming the jira server has https://marketplace.atlassian.com/plugins/atlassian-jira-markdown-plugin installed ?

**Comment by henvic** [comment]
We don't gain much adding logic for this.

Instead, let's just remove the markdown for Jira.

**Comment by maxandersen** [comment]
great!
