### ISSUE TITLE
Not allowing me to specify review request GitHub url

### ISSUE THREAD

**Issue by protoEvangelion** [node-gh/gh-jira#65]
When trying to transition the Jira issue to "Send for Review", it does not give me the option to specify the GitHub url of the PR.  Same thing happens in the hook after the PR is sent with `gh`.

**_Is that the intended functionality?_**

I noticed in the config there is this transition object which looks like it would allow specifying the PR url: 

```json
"transition": {
        "Code Review Request": {
            "Assignee": {
                "name": "{{options.assignee}}"
            },
            "Git Pull Request": "{{options.submittedLink}}"
        },
        "Create Review Request": {
            "Assignee": {
                "name": "{{options.assignee}}"
            },
            "Git Pull Request": "{{options.submittedLink}}"
        }
    }
```

**Comment by henvic** [comment]
I don't know. It's been a while since this was designed. Probably it just wasn't implemented. I am willing to accept a pull request with this feature.

**Comment by protoEvangelion** [comment]
@henvic Alrighty I will see what I can do!
