### ISSUE TITLE
how to disable this plugin per git repository

### ISSUE THREAD

**Issue by rotty3000** [node-gh/gh-jira#68]
Is it possible to disable gh-jira on a particular git repo? I use gh on several repos which use github issues. But because I have the gh-jira plugin installed it is hooked into the gh operations of every repo. I'd like to turn that off.

**Comment by henvic** [comment]
There is not.

**Comment by henvic** [comment]
The easiest thing would be to add a filter to the gh-jira project. Unfortunately, I don't have time to implement it.

If it's only for a single repository you might get away using an if conditional on your ~/.gh.json.
