### ISSUE TITLE
gh ji won't let me connect

### ISSUE THREAD

**Issue by julien** [node-gh/gh-jira#75]
Hi, 

I'm having trouble configuring this plugin (although it has worked for me in the past, and my credentials didn't change on the Jira side)

```sh
gh ji
# I Enter the same server info and credentials as if I was using my browser
```

Output: 

```sh
Writing GH config data.
warning: Not found any user when looking for 
```

**Comment by protoEvangelion** [comment]
Hey @julien if you download an an earlier version of gh like `v1.13.2` does that work?

**Comment by julien** [comment]
Hi @protoEvangelion 
Sorry for the late reply, this seems related to the server's configuration (which now requires a captcha when we login) rather than with this plugin. So I'm closing this for now. Sorry for the noise
